ARG BUILDER_IMAGE=debian:testing

FROM $BUILDER_IMAGE AS builder

ARG BUILD_SCRIPT=$BUILD_SCRIPT
ARG ARIA2_VER=$ARIA2_VER
ARG ZLIB=$ZLIB
ARG EXPAT=$EXPAT
ARG C_ARES=$C_ARES
ARG OPENSSL=$OPENSSL
ARG SQLITE3=$SQLITE3
ARG LIBSSH2=$LIBSSH2

COPY $BUILD_SCRIPT .

RUN bash $BUILD_SCRIPT

FROM scratch

COPY --from=builder /root/output /
