#
# Copyright (c) 2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Aria2-Pro-Core
#

name: Aria2 Builder

on:
  workflow_dispatch:
env:
  GITHUB_REPO: jsda/aria2-builder

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        PLATFORMS: [win64]
        include:
        - PLATFORMS: win64
          BUILDER_IMAGE: ubuntu:20.04
          BUILD_SCRIPT: aria2-gnu-linux-cross-build-win64.sh

    steps:

    - name: Install QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      env:
        DOCKER_BUILDKIT: 1
        BUILDER_IMAGE: ${{ matrix.BUILDER_IMAGE }}
        BUILD_SCRIPT: ${{ matrix.BUILD_SCRIPT }}
      run: |
        docker build \
          --build-arg BUILDER_IMAGE \
          --build-arg BUILD_SCRIPT \
          --platform=local \
          -o ./output . \
          2>&1 | tee build.log
          pwd

    - name: Output Error Log
      if: (!cancelled())
      run: grep -iE 'fatal|error|critical|failure|warning' build.log

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: aria2-${{ matrix.PLATFORMS }}
        path: output

    - name: Functional Testing
      run: |
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht.dat || echo "error"
        ./aria2c https://raw.githubusercontent.com/P3TERX/aria2.conf/master/dht6.dat || echo "error"
        ./aria2c \
          --seed-time=0 \
          --enable-dht6=true \
          --dht-file-path="$PWD/dht.dat" \
          --dht-file-path6="$PWD/dht6.dat" \
          --dht-entry-point='dht.transmissionbt.com:6881' \
          --dht-entry-point6='dht.transmissionbt.com:6881' \
          "$(curl -fsSL https://ubuntu.com/download/alternative-downloads | grep -o 'https.*server.*torrent' | head -1)" || echo "error"

