#
# This is free software, lisence use MIT.
#
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: update-version

on:
  workflow_dispatch:
  schedule:
    - cron: 20 0 * * 5
  repository_dispatch:
    types: [update-version]

permissions:
  contents: write

jobs:
  update-hashes:
    name: Update Makefile Hashes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true

    - name: Update
      id: compare
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./up.sh
        git config --global user.email "actions@github.com"
        git config --global user.name "actions"
        ARIA2_V=$(grep 'ARIA2_VER=' $GITHUB_WORKSPACE/dependences | cut -d'=' -f2)-$(date "+%Y%m%d")
        echo "ARIA2_V=$ARIA2_V" >> $GITHUB_OUTPUT
        echo "V_ER=$(cat $GITHUB_WORKSPACE/dependences)" >> $GITHUB_OUTPUT
        git add . && git commit -m "$ARIA2_V" && git push && echo "skip=false" >> $GITHUB_OUTPUT || echo "skip=true" >> $GITHUB_OUTPUT

    - name: Release Firmware
      if: ${{ steps.compare.outputs.skip != 'true' }}
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ steps.compare.outputs.ARIA2_V }}
        body_path: ${{ github.workspace }}/dependences
        body: |
          版本依赖：
          ${{ steps.compare.outputs.V_ER }}

    - name: Trigger release build
      if: steps.compare.outputs.skip == 'true'
      uses: peter-evans/repository-dispatch@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        event-type: aria2-builer
        client-payload: |
          {
            "release_tag": "v${{ steps.compare.outputs.ARIA2_V }}",
            "release_name": "Release v${{ steps.compare.outputs.ARIA2_V }}",
            "source_repository": "${{ github.event.client_payload.source_repository || github.repository }}",
            "triggered_by": "${{ github.event.client_payload.triggered_by || github.actor }}",
            "trigger_reason": "update-hashes"
          }

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 8
        keep_minimum_runs: 2
